version: '2'

services:      


    react:
        container_name: react
        stdin_open: true
        build:
            context: ../../builds/react
        command: npm start --host 0.0.0.0
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ../../source/practica1:/app
        environment:
            - CHOKIDAR_USEPOLLING=true